# Generated by Django 2.2.4 on 2019-08-29 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ALUMNOS',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('curso_nombre', models.CharField(max_length=25)),
                ('creditos', models.IntegerField()),
                ('ciclo', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=4)),
            ],
            options={
                'db_table': 'CURSOS',
            },
        ),
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id_alumno_curso', models.AutoField(primary_key=True, serialize=False)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Alumno')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Curso')),
            ],
            options={
                'db_table': 'ALUMNOS_CURSOS',
            },
        ),
    ]
